apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-redis
  labels:
    db: polar-redis
spec:
  selector:
    matchLabels:
      db: polar-redis
  template:
    metadata:
      labels:
        db: polar-redis
    spec:
      containers:
        - name: polar-redis
          image: redis:latest
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi