apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: polar-rabbitmq-config  
data:  
  enabled_plugins: |  
    [rabbitmq_management,rabbitmq_peer_discovery_k8s].  
  rabbitmq.conf: |  
    default_user = admin  
    default_pass = 123456  
    management.tcp.port = 15672